---
name: release binary

on:
  release:
    types: [created]

jobs:
  release-alpine-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker compose
        run: STAKE_TOKEN="ujunox" docker-compose up -d
      - name: Copy binary
        run: docker cp juno-node-1:/usr/bin/junod ./junod
      - name: Save sha256 sum
        run: sha256sum ./junod > ./junod_sha256.txt
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./junod
          asset_name: junod
          asset_content_type: application/octet-stream
      - name: Upload release sha sum
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./junod_sha256.txt
          asset_name: junod_sha256
          asset_content_type: application/octet-stream
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
